CREATE TABLE responces (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  percent_change_7d INTEGER NOT NULL,
  percent_change_24h INTEGER NOT NULL,
  price INTEGER NOT NULL
);