CREATE TABLE IF NOT EXISTS responces (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  percent_change_7d INTEGER NOT NULL,
  percent_change_24h INTEGER NOT NULL,
  price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS config (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  low_24h INTEGER NOT NULL,
  high_24h INTEGER NOT NULL,
  low_7d INTEGER NOT NULL,
  high_7d INTEGER NOT NULL
);

INSERT INTO config (low_24h, high_24h, low_7d, high_7d) VALUES (-100, 100, -200, 200)